config/routes.rb
Rails.application.routes.draw do
  
  root to: "couples#welcome"

  get "/login", to: "sessions#new"

  get "/sign_up", to: "couples#new"

  get "/couples/:id", to: "couples#show" , as: "couple"

  get "/sign_out", to: "sessions#destroy"

  post "/sessions", to: "sessions#create"


  resources :couples do 
    resources :registries 
  end

  resources :registries, shallow: true do
    resources :items
    resources :gifts
  end
  


end

app/models/couple.rb
class Couple < ActiveRecord::Base
	has_one :registry

	validates :name1, :name2, :email, :password_digest, presence: true, confirmation: true
	validates_uniqueness_of :email
	validates :password, length: {minimum: 1}

	has_secure_password

	def self.confirm(params)
		@couple = Couple.find_by({email: params[:email]})
	    @couple.try(:authenticate, params[:password_digest])
	end
end

app/models/gift.rb
class Gift < ActiveRecord::Base
	belongs_to :registry
	has_and_belongs_to_many :items
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :registry
	has_and_belongs_to_many :gifts
end

app/models/registry.rb
class Registry < ActiveRecord::Base
	belongs_to :couple 
	has_many :items, dependent: :destroy 
	has_many :gifts, dependent: :destroy 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
  include RegistriesHelper

end

app/controllers/couples_controller.rb
class CouplesController < ApplicationController
	before_action :logged_in?, only: [:show, :edit, :destroy, :update]
	
	def index
	end

	def new
		@couple = Couple.new

	end

	def create
	    @couple = Couple.new(couple_params)
	    if @couple.save
	      login(@couple)
	      redirect_to new_couple_registry_path(@couple)
	    else
	      render :new
	    end
	end

	def show
		@couple = Couple.find_by_id(params[:id])
		@registry = Registry.find_by couple_id: @couple.id
	end

	def destroy
	end

	def edit
		@couple = Couple.find(params[:id])
    	render :edit
	end

	def update
		@couple = Couple.find(params[:id])
		@couple.update(couple_params)
		redirect_to "/couples/#{@couple.id}"
	end 
	
	def welcome

	end

	private

	def couple_params
	  params.require(:couple).permit(:name1, :name2, :email, :password)
	end


end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  	def index
  	end

	def new
		item_ids = [13, 14, 15]
		@gift = Gift.new
		@gift.items = Item.find(item_ids)
	end

	def create
		@gift= Gift.new(gift_params)
		
		@current_item = current_couple #######!!! change
		
		@item_id = @gift.item.@curent_item.registry.id

		@registry = Registry.find_by item_id: @item_id
		@item.registry = Registry.find(@registry.id) #this is an inportant line 

		@item.save
		redirect_to edit_couple_registry_path(@couple_id, @registry.id)
	end

	def show
	end

	def destroy
	end

	def edit
	end

	def update
	end 

  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	def index
  	end

	def new
		@item = Item.new
		@registry = Registry.find_by_id(params[:registry_id])
		@current_couple = current_couple
  		if @current_couple
      	render :new
    	else
    	redirect_to sign_in_path
    	end
	end

	def create
		@item = Item.new(item_params)
		# @registry = Registry.find(@item.registry_id)
		@current_couple = current_couple
		@couple_id = current_couple.id
		@registry = Registry.find_by couple_id: @couple_id
		@item.registry = Registry.find(@registry.id) #this is an inportant line 

		@item.save
		redirect_to edit_couple_registry_path(@couple_id, @registry.id)

		
		# @couple = current_couple
		# @registry = Registry.find_by_id(params[:id])
	 #    if @item.save
	 #      redirect_to "/couples/#{@couple.id}/registries/#{@registry.id}"
	 #    else
	 #      redirect_to "/couples/#{@couple.id}"
	 #    end
	end

	def show
		@couple = current_couple
		@registry = Registry.find_by_id(params[:id])
		@items = Item.where registry_id: @registry.id
	end

	def destroy
		@item = Item.find_by_id(params[:id])
		@item.destroy

		@couple_id = current_couple.id
		@registry = Registry.find_by couple_id: @couple_id
		redirect_to edit_couple_registry_path(@couple_id, @registry.id)

		# @city = City.find_by_id(params[:city_id])
		# @all_comments = Comment.all.where(:post_id => @post.id)
		# @all_comments.destroy
		
		redirect_to edit_couple_registry_path
	end

	def edit
		@item = Item.find(params[:id])
		
		
		
	end

	def update
		@item = Item.all
		@couple = current_couple.id
		@registry = Registry.find_by couple_id: @couple
		redirect_to edit_couple_registry_path(@couple, @registry.id)
	end 

	private

	def item_params
	  params.require(:item).permit(:name, :price, :description)
	end

  
end

app/controllers/registries_controller.rb
class RegistriesController < ApplicationController
  	before_action :logged_in?, only: [:edit, :destroy, :update]

  	def index
    	
  	end

	def new
		@registry = Registry.new
		@current_couple = current_couple
  		if @current_couple
      	render :new
    	else
    	redirect_to sign_in_path
    	end
	end

	def create
		@registry = Registry.new(registry_params)
		@couple = current_couple
		@registry.couple = Couple.find(current_couple.id)
		# @couple = Couple.find_by_id(params[:registry_id])
		# @item = Item.find_by_id(@registry.item_id)
	    if @registry.save
	      # login(@registry)
	      redirect_to "/couples/#{@couple.id}/registries/#{@registry.id}"
	    else
	      redirect_to "/"
	    end
	end

	def show
		# this post
		@couple = current_couple
		@registry = Registry.find_by_id(params[:id])
		@items = Item.where registry_id: @registry.id
		
		

	
	end

	def destroy
	end

	def edit
		@couple = current_couple
		@registry = Registry.find_by_id(params[:id])
		@items = Item.where registry_id: @registry.id
    	render :edit
	end

	def update
		@couple = current_couple
		@registry = Registry.find_by_id(params[:id])
		@registry.update(registry_params)
		redirect_to edit_couple_registry_path(@couple.id, @registry)
	end 

	private
	  def registry_params 
	  	params.require(:registry).permit(:theam)
	  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


  def new
  	@couple = Couple.new
  	render :new 
  end

  def create
  	@couple = Couple.confirm(couple_params)
  	if @couple
  		login(@couple)
  		redirect_to "/couples/#{@couple.id}"
  	else
  	 	redirect_to sign_up_path
  	end
  end

  def destroy
  	logout
  	redirect_to root_path
  end

  private
  def couple_params 
  	params.require(:couple).permit(:email, :password_digest)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registries_helper.rb
module RegistriesHelper
	def exactUser
		@current_couple = Couple.find_by_id(session[:couple_id])
	end

	def commentUser(post)
		@comment_couple = Couple.find_by_id(registry.couple_id)
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper 
	def login(couple)
		session[:couple_id] = couple.id
		@current_couple = couple
	end

	def current_couple
		@current_couple ||= Couple.find_by_id(session[:couple_id])
	end

	def logged_in? 
		if current_couple == nil
			redirect_to login_path
		end
	end

	def signed_in?
		if current_couple == nil
			return false
		else
			return true
		end
	end

	def correct_couple(registries)
		if @current_couple.id == registries.couple_id
			return true
		else
			return false
		end
	end

	def logout
		@current_couple = session[:couple_id]= nil
	end
	
	def if_right_ucouple
	  @current_couple = exactUser
	  if @current_couple = !@current_couple
	    redirect_to login_path
	  end  
	end
	
end

app/views/couples/new.html.erb
<body class="welcome">
	<div class="container">
		<div class="row emailWidth">
        	<div class="col-md-12">
				<div class="wrap">
					<p class="form-title">
				        Sign Up</p>	
							<%= form_for @couple, url: "/couples", method: "post", :html => {:class => "loginForm"} do |f| %>
								<% if @couple.errors.any? %>
									<h3>Errors:</h3>
										<% @couple.errors.full_messages.each do |message| %>
											<h5><%= message %></h5>
										<% end %>
								<% end %>
								<%= f.text_field :name1, placeholder: "Name One", required: true, class: "emailSpace" %><br>
								<%= f.text_field :name2, placeholder: "Name Two", required: true, class: "emailSpace" %><br>
								<%= f.text_field :date, placeholder: "date of the wedding", required: true, class: "emailSpace" %><br>
								<%= f.email_field :email, placeholder: "Email", required: true, class: "emailSpace" %><br>
								<%= f.password_field :password, placeholder: "Password", required: true, class: "emailSpace" %><br>
								<%= f.password_field :password_confirmation, placeholder: "Password Confirmation", required: true, class: "emailSpace" %><br>
								<%= f.submit "Sign Up", class: "signInButton" %><br>
							<% end %>
							<div>
							  <div class="heart x1"></div>
							  <div class="heart x2"></div>
							  <div class="heart x3"></div>
							  <div class="heart x4"></div>
							  <div class="heart x5"></div>
							</div>
				</div>
			</div>
		</div>
	</div>
</body>

app/views/couples/show.html.erb
<div class="text-center">
	<% if signed_in? %>
		<h1 class="lead welcome-user font titleSize">Welcome, <%= @couple.name1 %> and <%= @couple.name2 %>! </h1>
	

	<button class="signInButton2"><%= link_to "Edit Registry", edit_couple_registry_path(@couple.id, @registry), method: :get%></button>

	<button class="signInButton2"><%= link_to "View Registry", couple_registry_path(@couple.id, @registry), method: :get%></button>



	<% end %> <!-- if sined in  -->
<div>

app/views/couples/welcome.html.erb
<body class="full">
	 <header class="image-bg-fluid-height img-center">
        
    </header>
	<div class="container">
		<div class="row">
		    <div class="col-md-6 col-sm-12">
				<h1  class="section-heading">Welcome</h1>
				<h3 class="lead section-lead">To your customizable wedding registry if you are not already a member please <%= link_to "Sign Up", "/sign_up" %> to start making your registry otherwise <%= link_to "Log In", "/login" %></h3>	
			</div>
			
		</div>
		<div>
		  	<div class="heart x1"></div>
		  	<div class="heart x2"></div>
		  	<div class="heart x3"></div>
		  	<div class="heart x4"></div>
		  	<div class="heart x5"></div>
		</div>
	</div>
</body>

app/views/gifts/new.html.erb
<p><%=form_for @gift, url:  registry_gifts_path, method: :post do |p|%></p>
	
		<% @gift.items.each do |f| %>
			
			<p> <%= f['name'] %></p>
			<p> <%= f['price'] %></p>
			<p> <%= f['description'] %></p>
			
			<hr>
		<% end %>


		<div class="input-group">
			<%=p.text_field :from, placeholder: "who is this from", required: true, class: "form-control" %>
		</div> <br>
		<div class="input-group">
			<%=p.text_area :message, placeholder: "Wright a mesage to the lovely couple", required: true, class: "form-control"%>
		</div> <br>
		
		<% @gift.items.each do |f| %>
		<%=p.hidden_field :Item_id, :multiple => true, value: f.id %>
		<% end %>

		<%=p.submit "add item", class: "btn btn-primary" %>
	
<%end%>

app/views/gifts/show.html.erb
show.html.erb

app/views/items/edit.html.erb
<h1>Edit</h1>
<%= form_for @item do |f| %>
	<%= f.text_field :name, placeholder: "name" %>
	<%= f.text_field :price, placeholder: "price" %>
	<%= f.text_field :description, placeholder: "description" %><br>
	<%= f.submit "save" %>

<% end %>

app/views/items/new.html.erb
<body class="welcome">	
	<div class="container">
		<div class="row emailWidth">
	        <div class="col-md-12">
				<div class="wrap">
					<p class="form-title">
						Add an Item </p>
					<%=form_for @item, url: registry_items_path(@registry.id), method: :post, :html => {:class => "loginForm"} do |p|%>
					
						<div class="input-group">
							<%=p.text_field :name, placeholder: "name", required: true, class: "emailSpace" %>
						</div> <br>
						<div class="input-group">
							<%=p.text_field :price, placeholder: "price", required: true, class: "emailSpace" %>
						</div> <br>
						<div class="input-group">
							<%=p.text_field :description, placeholder: "description", required: true, class: "emailSpace" %>
						</div> <br>
						
						<%=p.submit "add item", class: "signInButton2" %>
					
					<%end%>
				</div>
			</div>
		</div>
	</div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WeddingRegistry</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="backround">
<%= render "shared/header" %>
<%= yield %>

</body>
</html>

app/views/registries/edit.html.erb
<div>
	<div class="container">
		<% if signed_in? %>
			<div class="lead welcome-user"> 
				<p class="titleSize"><%= @couple.name1 %> and <%= @couple.name2 %> here is where you can edit your registry, your theam curently is </p>	
				<p class="center-block"> <%=form_for @registry, url: "/couples/#{@couple.id}/registries/#{@registry.id}", method: :put do |p|%></p>
						<div class="input-group">
							<%=p.text_field :theam, placeholder: "#{@registry.theam}", class: "form-control" %>
						</div> <span>
						<%=p.submit "Update Theam", class: "signInButton2" %>
						</span>
						<br>
						<hr>
				<%end%>
			</div>	

				<button class="signInButton2"><%= link_to "add Item", new_registry_item_path(@registry), method: :get%></button>
				<br>
				<hr>
				<% @items.each do |f| %>
					<p> <%= f['name'] %> </p> 
					<p> $<%= f['price'] %>.00</p>
					<p> <%= f['description'] %></p>
					<button class="signInButton2"><%= link_to "edit this item", edit_item_path%></button>
					<%= button_to "Delete Item", item_path, method: :delete, data: {confirm: "Are you sure?"}, class: "signInButton2" %>
				<br>
				<hr>
				<% end %>



				

		
		<%end%> <!-- if sined in -->
	
	</div>
</div>

app/views/registries/new.html.erb
<div class="container">
	<div class="row emailWidth">
		<div class="col-md-12">
			<div class="wrap">
				<p class="form-title">
			        What would you like your guests to help you buy</p>	
						<%= form_for @registry, url: couple_registries_path, method: "post", :html => {:class => "loginForm"} do |f| %>
							<% if @registry.errors.any? %>
								<h3>Errors:</h3>
									<% @registry.errors.full_messages.each do |message| %>
										<h5><%= message %></h5>
									<% end %>
							<% end %>
							<%= f.text_field :theam, placeholder: "what is your theam", required: true, class: "emailSpace" %><br>
							
							<%#=f.hidden_field :couple_id, value: @current_couple.id %> <br>
							<%= f.submit "Creat Registry", class: "signInButton" %><br>
						<% end %>
						<div>
						  <div class="heart x1"></div>
						  <div class="heart x2"></div>
						  <div class="heart x3"></div>
						  <div class="heart x4"></div>
						  <div class="heart x5"></div>
						</div>
			</div>
		</div>
	</div>
</div>

app/views/registries/show.html.erb
<header>
	<div class="row">
        <div class="col-lg-12">
            <img class="img-responsive gif" src="http://cdn.makeagif.com/media/10-29-2015/uEXL7p.gif" alt="">
			<div>
				<h1 class="name font">Welcome to</h1> <h1 class="name font"><%= @couple.name1 %> and <%= @couple.name2 %> registry!</h1>
				<br>
					<hr class="star-light">
				<h2 class="skills font">help them buy a <%= @registry.theam %></h2>
			</div>
</header>
<div class="container">
			<br>
			<p class="font size">Select an items of the boat from the list below and all the proseads will go twords alvin and sakina buying a boat.</p>
			<br>
			<hr>
			<div >

				<!-- option one  -->
				<script type="text/javascript">

					 var myFuncs = {
					  localstorage.setItem();
					};

					 $(".addItemPost").on("click", function(e){
					    myFuncs [data.func] ();
				</script>

				<!-- <button type="button" data-button='{"func": "localstorage.setItem()"}'>Select</button> -->

				<!-- option two -->
				<script type="text/javascript">
					$(".addItemPost").on("click", function(e) {
						var id=e.target.id
						var item = e.target.parent
						console.log(id)
						console.log(item)
						function what(t){
							localStorage.setItem(id, JSON.stringify("data-button"));
						};
					});
				</script>
				<% @items.each do |f| %>
				<button class="addItemPost pull-right signInButton2" data-button='{"func": "what"}' id="<%= f.id %>">select</button>	
					<p class="itemTitle"> <%= f.name %></p>
					<p class="font"> $<%= f.price %>.00</p>
					<ul class="font italic"> <%= f.description %></ul>
					<br>
					<hr>
				<% end %>
			</div>
		</div>
	</div>
</div>

	

	


</div> <!-- top of page div -->

app/views/shared/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-bottom" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                <% if signed_in? %>
					<li><%= link_to "Log Out", "/sign_out" %></li> 
                    <li><%= link_to "Home page", "/" %></li>
                        <% @current_couple = current_couple %>
                    <li><%= link_to "Profile", "/couples/#{@current_couple.id}" %></li>
				<% else %>
					<li><%= link_to "Log In", "/login" %></li>
					<li><%= link_to "Sign Up", "/sign_up" %></li>
                    <li><%= link_to "Home Page", "/" %></li>
				<% end %>    
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
</nav>